### ISSUE TITLE
Missing locations root leads to 500 once the app is deployed

### ISSUE THREAD

**Issue by lolautruche** [platformsh/platformify#167]
When using `project:init` using the "generic" stack for Upsun, the generated `config.yaml` is missing the `web.locations."/".root` property. It leads to a 500 error once the app is deployed.

```yaml
applications:
  myapp:
    type: php:8.2

    # ...

    web:
      locations:
        "/":
          root: "" # <--- This is the property missing
```
