### ISSUE TITLE
Validate command doesn't accept "pre_start" command

### ISSUE THREAD

**Issue by remilejeune2** [platformsh/platformify#190]
A `pre_start` command has been [introduced](https://docs.platform.sh/create-apps/app-reference.html#web-commands) a few month ago and it is not accepted by platformify.

To reproduce, use the following commands bloc:

```
        web:
          commands:
            pre_start: lkejzrezljkrzjlk
            start: ezrjklerzjlkerzjklzer
```

Then `upsun validate` gives you the following error:
```
Upsun config validation failed: applications.myapp.web.commands: Additional property pre_start is not allowed
```
