### ISSUE TITLE
[Upsun] `project:init` should generate relationships with the new format

### ISSUE THREAD

**Issue by lolautruche** [platformsh/platformify#196]
### Before

```yaml
   relationships:
      postgresql: "postgresql:postgresql"
```

### After
```yaml
  relationships:
    database:
      service: postgresql
      endpoint: postgresql
```

We may also consider using the new shorthand syntax:

```yaml
services: 
  pg_datatabase:
    type: postgresql:15

applications:
  app:
    type: 'php:8.2'
    relationships:
      # Defining relationships with null values,
      # using the services names as relationship names
      # 1st relationship below is an equivalent of:
      #pg_database:
      #  service: pg_database
      #  endpoint: postgresql
      pg_database:
```
