### ISSUE TITLE
Platformify should allow naming an app after one of the services we support

### ISSUE THREAD

**Issue by akalipetis** [platformsh/platformify#221]
Having the same name for an app and a service leads to an error, as we can't conclusively infer relationships.

Naming an app after our known services should not be allowed when running platformify.

Example config:

```
applications:
  mysql:
...
    relationships:
      mysql: "mysql:MySQL"
```

Error:
```
  E: Error parsing configuration files:
      - applications: Application 'mysql' already exists as a service.
  To git.eu-5.platform.sh:XXX.git
   ! [remote rejected] HEAD -> main (invalid configuration files)
  error: failed to push some refs to 'git.eu-5.platform.sh:XXX.git'
```
