### ISSUE TITLE
Endpoint definition is broken when relationships are included (new syntax)

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformify#222]
Creating a brand new application with services using the Upsun CLI (project:init) defaults to a broken relationship definition it seems. This is the content of my config.yaml :

```yaml
    relationships:
      postgresql:
        service: "postgresql"
        endpoint: "postgresql:postgresql"
      redis:
        service: "redis"
        endpoint: "redis:redis"
```
