### ISSUE TITLE
[Suggestion] Add instructional commands for build hook to match deploy hook, add more comments

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformify#87]
Current iteration of `project:init` creates a .platform.app.yaml that includes a comment block for the deploy hook:

```
  # The deploy hook runs after your application has been deployed and started.
  # Code cannot be modified at this point but the database is available.
  # The site is not accepting requests while this script runs so keep it
  # fast.
```
But does not include any information for the build hook. 

Suggestion is to add comments for the build hook and have both point to the docs for additional information. We could also add comments to the other sections:

```yaml
# Specifies a default set of build tasks to run. Flavors are language-specific.
# More information: https://docs.platform.sh/create-apps/app-reference.html#build
build:
    flavor: node|php

# Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
# are available in the PATH during the build process and in the runtime environment. They’re installed before
# the build hook runs using a package manager for the language.
# More information: https://docs.platform.sh/create-apps/app-reference.html#dependencies
dependencies:
    php|python(2|3)|ruby|nodejs|java:

# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
# More info:
hooks:
    # The build hook is run after any build flavor.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
    build: |
        set -e

    # The deploy hook is run after the app container has been started, but before it has started accepting requests.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook
    deploy: |
```
